apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: spark-history-serv
  name: spark-history-serv
  namespace: spark-history-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: spark-history-serv
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: spark-history-serv
      name: spark-history-serv
    spec:
      containers:
      - args:
        - /opt/spark/bin/spark-class 
        - org.apache.spark.deploy.history.HistoryServer
        command:
        - '/opt/entrypoint.sh'
        image: mragesh/spark:spark-history
        imagePullPolicy: Always
        name: spark-history-serv
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
